teams_dict={ 
'Atlanta Hawks' :'ATL'	 ,
'Brooklyn Nets' :'BKN'	 ,
'Boston Celtics' :'BOS'	 ,
'Charlotte Hornets' :'CHA'	 ,
'Chicago Bulls' :'CHI'	 ,
'Cleveland Cavaliers' :'CLE'	 ,
'Dallas Mavericks' :'DAL'	 ,
'Denver Nuggets' :'DEN'	 ,
'Detroit Pistons' :'DET'	 ,
'Golden State Warriors' :'GS'	 ,
'Houston Rockets' :'HOU'	 ,
'Indiana Pacers' :'IND'	 ,
'L.A. Clippers' :'LAC'	 ,
'L.A. Lakers' :'LAL'	 ,
'Memphis Grizzlies' :'MEM'	 ,
'Miami Heat' :'MIA'	 ,
'Milwaukee Bucks' :'MIL'	 ,
'Minnesota Timberwolves' :'MIN'	 ,
'New Orleans Pelicans' :'NO'	 ,
'New York Knicks' :'NY'	 ,
'Oklahoma City Thunder' :'OKC'	 ,
'Orlando Magic' :'ORL'	 ,
'Philadelphia 76ers' :'PHI'	 ,
'Phoenix Suns' :'PHO'	 ,
'Portland Trail Blazers' :'POR'	 ,
'Sacramento Kings' :'SAC'	 ,
'San Antonio Spurs' :'SA'	 ,
'Toronto Raptors' :'TOR'	 ,
'Utah Jazz' :'UTA'	 ,
'Washington Wizards'   :'WAS'	  
} 