city_dict={ 
'Atlanta' :'ATL'	 ,
'Brooklyn' :'BKN'	 ,
'Boston' :'BOS'	 ,
'Charlotte' :'CHA'	 ,
'Chicago' :'CHI'	 ,
'Cleveland' :'CLE'	 ,
'Dallas' :'DAL'	 ,
'Denver' :'DEN'	 ,
'Detroit' :'DET'	 ,
'Golden State ' :'GSW'	 ,
'Houston Rockets' :'HOU'	 ,
'Indiana Pacers' :'IND'	 ,
'L.A. Clippers' :'LAC'	 ,
'L.A. Lakers' :'LAL'	 ,
'Memphis Grizzlies' :'MEM'	 ,
'Miami Heat' :'MIA'	 ,
'Milwaukee Bucks' :'MIL'	 ,
'Minnesota Timberwolves' :'MIN'	 ,
'New Orleans Pelicans' :'NOP'	 ,
'New York Knicks' :'NYK'	 ,
'Oklahoma City Thunder' :'OKC'	 ,
'Orlando Magic' :'ORL'	 ,
'Philadelphia 76ers' :'PHI'	 ,
'Phoenix Suns' :'PHX'	 ,
'Portland Trail Blazers' :'POR'	 ,
'Sacramento Kings' :'SAC'	 ,
'San Antonio Spurs' :'SAS'	 ,
'Toronto Raptors' :'TOR'	 ,
'Utah Jazz' :'UTA'	 ,
'Washington Wizards'   :'WSH'	  
} 